backup-auto-remove: 7 # Automatically deletes backups older than the specified number of days
backup-interval: 86400 # Automatic backup interval in seconds
world-name: world # The name of the world where playerdata is stored
language: "en_US" # Language